include_recipe "applications::packagemanager"
include_recipe "git::default"
include_recipe "skylab::postgresql"
include_recipe "applications::mysql"
include_recipe "skylab::apache"
include_recipe "applications::php55"
include_recipe "skylab::directories"
